# Generated by Django 5.2.7 on 2025-10-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bharu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.URLField(null=True),
        ),
    ]
