# Generated by Django 5.2.7 on 2025-10-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bharu', '0003_post_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
