# Generated by Django 5.2.7 on 2025-11-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bharu', '0005_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
